// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "buf.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace thread_msg {

namespace {

const ::google::protobuf::Descriptor* Thread_Data_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Thread_Data_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_buf_2eproto() {
  protobuf_AddDesc_buf_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "buf.proto");
  GOOGLE_CHECK(file != NULL);
  Thread_Data_descriptor_ = file->message_type(0);
  static const int Thread_Data_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Thread_Data, cluster_),
  };
  Thread_Data_reflection_ =
    new ::google::protobuf::internal::GeneratedMessageReflection(
      Thread_Data_descriptor_,
      Thread_Data::default_instance_,
      Thread_Data_offsets_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Thread_Data, _has_bits_[0]),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Thread_Data, _unknown_fields_),
      -1,
      ::google::protobuf::DescriptorPool::generated_pool(),
      ::google::protobuf::MessageFactory::generated_factory(),
      sizeof(Thread_Data));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_buf_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
    Thread_Data_descriptor_, &Thread_Data::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_buf_2eproto() {
  delete Thread_Data::default_instance_;
  delete Thread_Data_reflection_;
}

void protobuf_AddDesc_buf_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\tbuf.proto\022\nthread_msg\"\036\n\013Thread_Data\022\017"
    "\n\007cluster\030\001 \003(\t", 55);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "buf.proto", &protobuf_RegisterTypes);
  Thread_Data::default_instance_ = new Thread_Data();
  Thread_Data::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_buf_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_buf_2eproto {
  StaticDescriptorInitializer_buf_2eproto() {
    protobuf_AddDesc_buf_2eproto();
  }
} static_descriptor_initializer_buf_2eproto_;

// ===================================================================

#ifndef _MSC_VER
const int Thread_Data::kClusterFieldNumber;
#endif  // !_MSC_VER

Thread_Data::Thread_Data()
  : ::google::protobuf::Message() {
  SharedCtor();
  // @@protoc_insertion_point(constructor:thread_msg.Thread_Data)
}

void Thread_Data::InitAsDefaultInstance() {
}

Thread_Data::Thread_Data(const Thread_Data& from)
  : ::google::protobuf::Message() {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:thread_msg.Thread_Data)
}

void Thread_Data::SharedCtor() {
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
}

Thread_Data::~Thread_Data() {
  // @@protoc_insertion_point(destructor:thread_msg.Thread_Data)
  SharedDtor();
}

void Thread_Data::SharedDtor() {
  if (this != default_instance_) {
  }
}

void Thread_Data::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Thread_Data::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Thread_Data_descriptor_;
}

const Thread_Data& Thread_Data::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_buf_2eproto();
  return *default_instance_;
}

Thread_Data* Thread_Data::default_instance_ = NULL;

Thread_Data* Thread_Data::New() const {
  return new Thread_Data;
}

void Thread_Data::Clear() {
  cluster_.Clear();
  ::memset(_has_bits_, 0, sizeof(_has_bits_));
  mutable_unknown_fields()->Clear();
}

bool Thread_Data::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:thread_msg.Thread_Data)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated string cluster = 1;
      case 1: {
        if (tag == 10) {
         parse_cluster:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_cluster()));
          ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
            this->cluster(this->cluster_size() - 1).data(),
            this->cluster(this->cluster_size() - 1).length(),
            ::google::protobuf::internal::WireFormat::PARSE,
            "cluster");
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_cluster;
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormat::SkipField(
              input, tag, mutable_unknown_fields()));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:thread_msg.Thread_Data)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:thread_msg.Thread_Data)
  return false;
#undef DO_
}

void Thread_Data::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:thread_msg.Thread_Data)
  // repeated string cluster = 1;
  for (int i = 0; i < this->cluster_size(); i++) {
  ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
    this->cluster(i).data(), this->cluster(i).length(),
    ::google::protobuf::internal::WireFormat::SERIALIZE,
    "cluster");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      1, this->cluster(i), output);
  }

  if (!unknown_fields().empty()) {
    ::google::protobuf::internal::WireFormat::SerializeUnknownFields(
        unknown_fields(), output);
  }
  // @@protoc_insertion_point(serialize_end:thread_msg.Thread_Data)
}

::google::protobuf::uint8* Thread_Data::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:thread_msg.Thread_Data)
  // repeated string cluster = 1;
  for (int i = 0; i < this->cluster_size(); i++) {
    ::google::protobuf::internal::WireFormat::VerifyUTF8StringNamedField(
      this->cluster(i).data(), this->cluster(i).length(),
      ::google::protobuf::internal::WireFormat::SERIALIZE,
      "cluster");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(1, this->cluster(i), target);
  }

  if (!unknown_fields().empty()) {
    target = ::google::protobuf::internal::WireFormat::SerializeUnknownFieldsToArray(
        unknown_fields(), target);
  }
  // @@protoc_insertion_point(serialize_to_array_end:thread_msg.Thread_Data)
  return target;
}

int Thread_Data::ByteSize() const {
  int total_size = 0;

  // repeated string cluster = 1;
  total_size += 1 * this->cluster_size();
  for (int i = 0; i < this->cluster_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->cluster(i));
  }

  if (!unknown_fields().empty()) {
    total_size +=
      ::google::protobuf::internal::WireFormat::ComputeUnknownFieldsSize(
        unknown_fields());
  }
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Thread_Data::MergeFrom(const ::google::protobuf::Message& from) {
  GOOGLE_CHECK_NE(&from, this);
  const Thread_Data* source =
    ::google::protobuf::internal::dynamic_cast_if_available<const Thread_Data*>(
      &from);
  if (source == NULL) {
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
    MergeFrom(*source);
  }
}

void Thread_Data::MergeFrom(const Thread_Data& from) {
  GOOGLE_CHECK_NE(&from, this);
  cluster_.MergeFrom(from.cluster_);
  mutable_unknown_fields()->MergeFrom(from.unknown_fields());
}

void Thread_Data::CopyFrom(const ::google::protobuf::Message& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Thread_Data::CopyFrom(const Thread_Data& from) {
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Thread_Data::IsInitialized() const {

  return true;
}

void Thread_Data::Swap(Thread_Data* other) {
  if (other != this) {
    cluster_.Swap(&other->cluster_);
    std::swap(_has_bits_[0], other->_has_bits_[0]);
    _unknown_fields_.Swap(&other->_unknown_fields_);
    std::swap(_cached_size_, other->_cached_size_);
  }
}

::google::protobuf::Metadata Thread_Data::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Thread_Data_descriptor_;
  metadata.reflection = Thread_Data_reflection_;
  return metadata;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace thread_msg

// @@protoc_insertion_point(global_scope)
