// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: buf.proto

#ifndef PROTOBUF_buf_2eproto__INCLUDED
#define PROTOBUF_buf_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2006000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2006001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)

namespace thread_msg {

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_buf_2eproto();
void protobuf_AssignDesc_buf_2eproto();
void protobuf_ShutdownFile_buf_2eproto();

class Thread_Data;

// ===================================================================

class Thread_Data : public ::google::protobuf::Message {
 public:
  Thread_Data();
  virtual ~Thread_Data();

  Thread_Data(const Thread_Data& from);

  inline Thread_Data& operator=(const Thread_Data& from) {
    CopyFrom(from);
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }

  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }

  static const ::google::protobuf::Descriptor* descriptor();
  static const Thread_Data& default_instance();

  void Swap(Thread_Data* other);

  // implements Message ----------------------------------------------

  Thread_Data* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Thread_Data& from);
  void MergeFrom(const Thread_Data& from);
  void Clear();
  bool IsInitialized() const;

  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated string cluster = 1;
  inline int cluster_size() const;
  inline void clear_cluster();
  static const int kClusterFieldNumber = 1;
  inline const ::std::string& cluster(int index) const;
  inline ::std::string* mutable_cluster(int index);
  inline void set_cluster(int index, const ::std::string& value);
  inline void set_cluster(int index, const char* value);
  inline void set_cluster(int index, const char* value, size_t size);
  inline ::std::string* add_cluster();
  inline void add_cluster(const ::std::string& value);
  inline void add_cluster(const char* value);
  inline void add_cluster(const char* value, size_t size);
  inline const ::google::protobuf::RepeatedPtrField< ::std::string>& cluster() const;
  inline ::google::protobuf::RepeatedPtrField< ::std::string>* mutable_cluster();

  // @@protoc_insertion_point(class_scope:thread_msg.Thread_Data)
 private:

  ::google::protobuf::UnknownFieldSet _unknown_fields_;

  ::google::protobuf::uint32 _has_bits_[1];
  mutable int _cached_size_;
  ::google::protobuf::RepeatedPtrField< ::std::string> cluster_;
  friend void  protobuf_AddDesc_buf_2eproto();
  friend void protobuf_AssignDesc_buf_2eproto();
  friend void protobuf_ShutdownFile_buf_2eproto();

  void InitAsDefaultInstance();
  static Thread_Data* default_instance_;
};
// ===================================================================


// ===================================================================

// Thread_Data

// repeated string cluster = 1;
inline int Thread_Data::cluster_size() const {
  return cluster_.size();
}
inline void Thread_Data::clear_cluster() {
  cluster_.Clear();
}
inline const ::std::string& Thread_Data::cluster(int index) const {
  // @@protoc_insertion_point(field_get:thread_msg.Thread_Data.cluster)
  return cluster_.Get(index);
}
inline ::std::string* Thread_Data::mutable_cluster(int index) {
  // @@protoc_insertion_point(field_mutable:thread_msg.Thread_Data.cluster)
  return cluster_.Mutable(index);
}
inline void Thread_Data::set_cluster(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:thread_msg.Thread_Data.cluster)
  cluster_.Mutable(index)->assign(value);
}
inline void Thread_Data::set_cluster(int index, const char* value) {
  cluster_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:thread_msg.Thread_Data.cluster)
}
inline void Thread_Data::set_cluster(int index, const char* value, size_t size) {
  cluster_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:thread_msg.Thread_Data.cluster)
}
inline ::std::string* Thread_Data::add_cluster() {
  return cluster_.Add();
}
inline void Thread_Data::add_cluster(const ::std::string& value) {
  cluster_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:thread_msg.Thread_Data.cluster)
}
inline void Thread_Data::add_cluster(const char* value) {
  cluster_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:thread_msg.Thread_Data.cluster)
}
inline void Thread_Data::add_cluster(const char* value, size_t size) {
  cluster_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:thread_msg.Thread_Data.cluster)
}
inline const ::google::protobuf::RepeatedPtrField< ::std::string>&
Thread_Data::cluster() const {
  // @@protoc_insertion_point(field_list:thread_msg.Thread_Data.cluster)
  return cluster_;
}
inline ::google::protobuf::RepeatedPtrField< ::std::string>*
Thread_Data::mutable_cluster() {
  // @@protoc_insertion_point(field_mutable_list:thread_msg.Thread_Data.cluster)
  return &cluster_;
}


// @@protoc_insertion_point(namespace_scope)

}  // namespace thread_msg

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_buf_2eproto__INCLUDED
